name: Publish

on:
  push:
    tags: ['v*']

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: swift build
      - name: Test
        run: swift test
      - name: Resolve dependencies
        run: swift package resolve
      - uses: anchore/sbom-action@3ad7283483fc7af8ff2b4ea19663c2d5ca935e26 # v0.24.2
        with:
          path: .
          format: cyclonedx-json
          output-file: kmip-swift-${{ github.ref_name }}-sbom.cyclonedx.json
          syft-version: v1.54.0
          upload-artifact: false
      - uses: anchore/sbom-action@3ad7283483fc7af8ff2b4ea19663c2d5ca935e26 # v0.24.2
        with:
          path: .
          format: spdx-json
          output-file: kmip-swift-${{ github.ref_name }}-sbom.spdx.json
          syft-version: v1.54.0
          upload-artifact: false
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: sbom
          path: kmip-swift-*-sbom.*.json
